server:
  port: 7778

spring:
  datasource:
    url: jdbc:mysql://111.231.15.64:3306/sg_blog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jicredt
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  redis:
    host: 111.231.15.64
    port: 6379
    database: 1
    password: frank

  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

minio:
  endpoint: https://o5i1850274.zicp.fun
  accessKey: sg_blog_frank
  secretKey: frank0814
  filHost: 192.168.110.243:9091
  bucketName: sg-blog
